authentication/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'authentication'
urlpatterns = [
    path('login', LoginView.as_view(template_name="login.html"), name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', LogoutView.as_view(next_page='authentication:login'), name='logout'),
]

dnd/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from dnd_app import views as dnd_app_views
from . import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('', include('dnd_app.urls'), name='dnd_app'),
    path('authentication/', include('authentication.urls'), name='authentication'),
]

dnd_app/urls.py
from django.urls import path
from . import views

app_name = 'dnd_app'
urlpatterns = [
    path('character_creator/', views.character_creator, name='character_creator'),
    path('coin_converter/', views.coin_converter, name='coin_converter'),
    path('bestiary/', views.bestiary, name='bestiary'),
]

authentication/models.py
from django.db import models

# Create your models here.

dnd_app/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate

from django.http import HttpResponse

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponse("Signed up")
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

dnd/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    context = {
        "current_page": "home"
    }
    return render(request, "home.html", context)

dnd_app/views.py
from django.shortcuts import render

# Create your views here.
def character_creator(request):
    context = {
        "current_page": "character_creator"
    }
    return render(request, "character_creator.html", context)

def coin_converter(request):
    context = {
        "current_page": "coin_converter"
    }
    return render(request, "coin_converter.html", context)

def bestiary(request):
    context = {
        "current_page": "bestiary"
    }
    return render(request, "bestiary.html", context)

authentication/templates/login.html
<h2>Login</h2>
<form method="post">
{% csrf_token %}
<p>{{ form.username }}</p>
<p>{{ form.password }}</p>
<div style="color:red">{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
</div>
<input type="submit" value="Login" class="btn btn-primary"></input>
</form>

authentication/templates/signup.html
<h2>Sign up</h2>
<form method="post">
{% csrf_token %}
{{ form }}

{% if form.errors %}
<div style="color:red">
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
</div>
{% endif %}

<br>
<input type="submit" value="Sign up" class="btn btn-primary"></input>
</form>

dnd_app/templates/bestiary.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Bestiary
{% endblock %}

{% block content %}
<div id="bestiary_react"></div>
<script type="text/babel" src="{% static 'src/bestiary.jsx' %}"></script>
{% endblock %}

dnd_app/templates/character_creator.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Character Creator
{% endblock %}

{% block content %}
<div id="character_creator_react"></div>
<script type="text/babel" src="{% static 'src/character_creator.jsx' %}"></script>
{% endblock %}

dnd_app/templates/coin_converter.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Coin Converter
{% endblock %}

{% block content %}
<div id="coin_converter_react"></div>
<script type="text/babel" src="{% static 'src/coin_converter.jsx' %}"></script>
{% endblock %}

templates/base.html
{% load static %}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- JQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js"></script>
    
    <!-- FontAwesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
    
    <!-- React CDN -->
    <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    
    <!-- Babel CDN -->
    <script src="https://unpkg.com/@babel/standalone@7.15.7/babel.min.js"></script>
    
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <i class="fas fa-dragon"></i> D&D5e Tools
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link{% if current_page == 'home' %} active{% endif %}" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{% if current_page == 'character_creator' %} active{% endif %}" href="{% url 'dnd_app:character_creator' %}">Character Creator</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{% if current_page == 'coin_converter' %} active{% endif %}" href="{% url 'dnd_app:coin_converter' %}">Coin Converter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link{% if current_page == 'bestiary' %} active{% endif %}" href="{% url 'dnd_app:bestiary' %}">Bestiary</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div id="content" class="container">
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer" class="bg-light mt-5">
        <div class="container" style="text-align: center;">
            <div class="mb-2">Created by <a href="https://brandonssandbox.com/">Brandon Lee</a>, 2021.</div>
            <a href="" target="_blank"><img src="https://img.shields.io/badge/-Check_out_my_GitHub-blue?logo=github&logoColor=white"></a>
            <a href="" target="_blank"><img src="https://img.shields.io/badge/-Buy_me_a_coffee!-orange?logo=buymeacoffee&logoColor=white"></a>
        </div>
    </div>
</body>

templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1 class="mt-5">Brandon's D&D5e Tools</h1>
<p>
    Welcome to <i>Brandon's D&D5e Tools</i>, a set of online tools designed to help players (especially new players) navigate D&D5e.
    This creator relies on the <a href="https://www.dndbeyond.com">D&D Beyond</a> website for a lot of its content (e.g. images, descriptions, or rules).
    These projects are not commercial and cedes all rights to the original creators of D&D.
</p>
<p>Check out my <a href="https://brandonssandbox.com/">personal website</a> and <a href="https://github.com/dabslee">GitHub</a> for more of my projects, or <a href="">buy me a coffee</a> to support my work!</p>
<div class="d-flex flex-sm-row flex-column justify-content-between mt-4">
    <a href="{% url 'dnd_app:character_creator' %}" class="card col-sm-4 text-center selectable-project mb-3">
        <div class="card-body">
            <h5>Character Creator</h5>
            <p>A step-by-step D&D5e character builder.</p>
            <img src="https://www.dndbeyond.com/avatars/thumbnails/6/258/420/618/636271801914013762.png" style="width: 15rem"/>
        </div>
    </a>
    <a href="{% url 'dnd_app:character_creator' %}" class="card col-sm-4 text-center selectable-project mb-3">
        <div class="card-body">
            <h5>Coin Converter</h5>
            <p>A tool to convert a set of currencies (cp, sp, etc.) to a single currency of your choosing.</p>
            <img src="http://assets.stickpng.com/images/58a1e96ec8dd3432c6fa81c6.png" style="width: 15rem"/>
        </div>
    </a>
    <div class="col-sm-3 mb-3">
        <h5>Other useful projects:</h5>
        <p class="text-muted"><i>(By people other than me)</i></p>
        <a href="https://www.dndbeyond.com/" class="card selectable-project mb-3">
            <div class="card-body">
                <h5>D&D5e Beyond <i class="fas fa-dragon"></i></h5>
                <p>The official digital toolset and game companion for D&D5e.</p>
            </div>
        </a>
        <a href="https://dice.run/" class="card selectable-project mb-3">
            <div class="card-body">
                <h5>dice.run <i class="fas fa-dice"></i></h5>
                <p>A remarkably queryable/customizable digital dice roll simulator.</p>
            </div>
        </a>
        <a href="https://5e.tools/" class="card selectable-project">
            <div class="card-body">
                <h5>5e.tools <i class="fas fa-book"></i></h5>
                <p>An comprehensive encyclopedia of rules and monsters in an easily queriable and usable format.</p>
            </div>
        </a>
    </div>
</div>
{% endblock %}